### ISSUE TITLE
Consider using a different keywork declaration (use val instead of const)

### ISSUE THREAD

**Issue by opensas** [voltrevo/ValueScript#12]
This is more a question than an issue

Have you considered using a different keyword, like `val` (meaning value similar to scala) instead of `const`.

I find it confusing that the same keyword would work completely different from JavaScript (and Typescript) on a perfectly valid ts code base, depending whether we are using ValueScript or not.

It seems like `const` has been chosen by design, to keep ValueScript syntax compatible with TypeScript, but I think i ends up being really confusing.

On the other hand, having a new and distinct `val` variable declaration, that declares an immutable value, would be much more clear (in fact, I think JavaScript should directly support such a thing)

Anyway, this is an excellent project, and I think it's meant to fill an obvious and much needed hole in JavaScript spec. I only wish this project is successful enough to make people at CT39 realize how badly JavaScript needs this feature to keep evolving.

**Comment by voltrevo** [comment]
Hi @opensas 👋

I think this point actually applies more generally. The downside of this dialect approach where I'm redefining the behavior of the same syntax - that can be confusing. There's also the upside of tooling compatibility and a much easier transition than learning a new language.

I think it's more positive than negative, but it's definitely something to keep in mind as we learn more about what it's like to use ValueScript. It's very possible we'll eventually pivot and deviate from TypeScript a bit more to make it more of its own language than just a dialect.

For the moment, using `val` is a non-starter because we rely on SWC for parsing and benefit hugely from TypeScript tooling because of 100% syntax compatibility. If this does ever change we'll need to do a language server for intellisense and define syntax highlighting and all that, but for the time being that just takes care of itself.

Personally I'd quite like to adopt rust's `mut` so that we have constness by default instead of mutability by default.

> Anyway, this is an excellent project

Thanks 💪
